import Stage from '../ui/Stage';
import Panel from '../ui/Panel';
import JellyButton from '../ui/JellyButton';
import type { CreditsView } from '../audio/credits.js';
import s from './Credits.module.css';

export interface CreditsProps {
  view: CreditsView;
  onBack?: () => void;
}

const Source = ({ url, children }: { url: string | undefined; children: string }) =>
  url ? <a className={s.link} href={url} target="_blank" rel="noreferrer">{children}</a> : <span>{children}</span>;

/**
 * Who made what the game sounds like (M14 ticket 14, ADR 0087 amendment):
 * every CC-BY work with the credit its licence asks for, thanks to the CC0
 * authors whose work needs none, and where the music came from. Built from
 * `public/sounds/CREDITS.md`, so nothing shipped goes uncredited.
 */
export default function Credits({ view, onBack }: CreditsProps) {
  return (
    <Stage background="var(--df-stage-lobby)" sheen="var(--df-sheen-menu)" className={s.screen}>
      <div className={s.topbar}>
        <span className={s.title}>CREDITS</span>
      </div>

      <Panel className={s.panel}>
        <section className={s.section} aria-label="Sound, with attribution">
          <h2 className={s.heading}>SOUND</h2>
          <ul className={s.list}>
            {view.attribution.map((line) => (
              <li key={`${line.title}·${line.author}`} className={s.line}>
                <span className={s.work}>
                  <Source url={line.url}>{line.title}</Source>
                </span>
                <span className={s.by}>by {line.author}</span>
                <span className={s.licence}>{line.licence}</span>
              </li>
            ))}
          </ul>
        </section>

        <section className={s.section} aria-label="With thanks">
          <h2 className={s.heading}>WITH THANKS · CC0</h2>
          <ul className={s.list}>
            {view.thanks.map(({ author, works }) => (
              <li key={author} className={s.line}>
                <span className={s.work}>{author}</span>
                <span className={s.by}>
                  {works.map((work, i) => (
                    <span key={work.title}>
                      {i > 0 && ', '}
                      <Source url={work.url}>{work.title}</Source>
                    </span>
                  ))}
                </span>
              </li>
            ))}
          </ul>
        </section>

        <section className={s.section} aria-label="Music">
          <h2 className={s.heading}>MUSIC</h2>
          <p className={s.note}>
            Music generated by the game&apos;s author
            {view.musicTools.length > 0 ? ` with ${view.musicTools.join(' and ')}` : ''}.
          </p>
        </section>
      </Panel>

      <div className={s.actions}>
        <JellyButton variant="pill" tone="glass" centered sound="back" onClick={onBack}>BACK</JellyButton>
      </div>
    </Stage>
  );
}
