// @vitest-environment jsdom
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { fireEvent, render, screen, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes, useNavigate } from "react-router";
import { describe, expect, it, vi } from "vitest";
import { creditsView, parseSoundCredits } from "../audio/credits.js";
import Credits from "./Credits.js";
import { CreditsRoute } from "./CreditsRoute.js";

const markdown = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "..", "public", "sounds", "CREDITS.md"), "utf8");
const view = creditsView(parseSoundCredits(markdown));

describe("the Credits Screen (M14 ticket 14)", () => {
  it("names every CC-BY work with its author, licence and source", () => {
    render(<Credits view={view} />);
    const sound = within(screen.getByRole("region", { name: "Sound, with attribution" }));
    for (const line of view.attribution) {
      const title = sound.getByRole("link", { name: line.title });
      expect(title).toHaveAttribute("href", line.url);
      const row = title.closest("li")!;
      expect(row).toHaveTextContent(`by ${line.author}`);
      expect(row).toHaveTextContent(line.licence);
    }
    expect(sound.getByText("by Cyril Laurier")).toBeInTheDocument();
    expect(sound.getByText("by mwl500")).toBeInTheDocument();
  });

  it("thanks Kenney and the other CC0 authors, and says where the music came from", () => {
    render(<Credits view={view} />);
    const thanks = within(screen.getByRole("region", { name: "With thanks" }));
    expect(thanks.getByText("Kenney (www.kenney.nl)")).toBeInTheDocument();
    expect(thanks.getByRole("link", { name: "Impact Sounds" })).toHaveAttribute("href", "https://kenney.nl/assets/impact-sounds");
    // The jump's author, with the page it came from (user, 2026-09-17).
    const jump = thanks.getByRole("link", { name: "JUMP SFX RANDOMISATION - HUMAN MADE" });
    expect(jump).toHaveAttribute("href", "https://freesound.org/people/CCOUNTERFEIT/sounds/851416/");
    expect(jump.closest("li")).toHaveTextContent("CCOUNTERFEIT");
    expect(screen.getByRole("region", { name: "Music" })).toHaveTextContent(
      "Music generated by the game's author with Stable Audio and Suno.",
    );
  });

  it("goes back", () => {
    const onBack = vi.fn();
    render(<Credits view={view} onBack={onBack} />);
    fireEvent.click(screen.getByRole("button", { name: "BACK" }));
    expect(onBack).toHaveBeenCalledTimes(1);
  });

  it("is reached at /credits, built from the shipped CREDITS.md, and BACK returns where the Player was", () => {
    const Settings = () => {
      const navigate = useNavigate();
      return (
        <button type="button" onClick={() => navigate("/credits")}>
          open credits
        </button>
      );
    };
    render(
      <MemoryRouter initialEntries={["/settings"]}>
        <Routes>
          <Route path="/settings" element={<Settings />} />
          <Route path="/credits" element={<CreditsRoute />} />
        </Routes>
      </MemoryRouter>,
    );
    fireEvent.click(screen.getByText("open credits"));
    expect(screen.getByRole("link", { name: "XRayBelt.aif" })).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "BACK" }));
    expect(screen.getByText("open credits")).toBeInTheDocument();
  });
});
