import type { MatchPhase } from "@dont-fall/shared";
import { musicGain, readAudioVolumes, subscribeAudioVolumes } from "../lib/audioSettings.js";
import { browserStorage } from "../lib/perfFlag.js";
import { sharedAudioContext } from "./sharedContext.js";
import { SOUNDS_BASE_URL } from "./soundBank.js";

/**
 * Music (M14 ticket 11, ADR 0087): the Lobby's playlist and the Round's, each
 * shuffled, streamed through media elements rather than decoded whole.
 *
 * The app's music, not a Screen's (user, 2026-09-17): the Lobby's playlist
 * plays on every React Screen and in free roam, from the first gesture on,
 * and carries on across navigation. Only a Match's Round switches to the
 * Round's playlist, and leaving the Match brings the Lobby's back.
 *
 * Three-free and Stage-free: the menu plays music before any game module
 * loads, and the music outlives every Stage (a Track swap). So the player has
 * its own chain on the page's shared context, and applies the MASTER and
 * MUSIC sliders itself. The Stage's music bus stays unused.
 */

export type Playlist = "lobby" | "round";

/** The tracks, generated by the game's author (ADR 0087 amendment), under `public/sounds/`. */
export const MUSIC_PLAYLISTS: Readonly<Record<Playlist, readonly string[]>> = {
  lobby: ["music/lobby_0.ogg", "music/lobby_1.ogg", "music/lobby_2.ogg"],
  round: ["music/round_0.ogg", "music/round_1.ogg", "music/round_2.ogg", "music/round_3.ogg", "music/round_4.ogg"],
};

/** What a phase plays: the Lobby's playlist, or the Round's, ducked under the jingles that end a Round. */
export const musicFor = (phase: MatchPhase): { playlist: Playlist; ducked: boolean } =>
  phase === "LOBBY" ? { playlist: "lobby", ducked: false } : { playlist: "round", ducked: phase === "ROUND_END" || phase === "RESULTS" };

/** A shuffled pick from `tracks` that is never `last` (while there is anything else to play). */
export const nextTrack = (tracks: readonly string[], last: string | undefined, random: () => number = Math.random): string => {
  const choices = tracks.length > 1 ? tracks.filter((track) => track !== last) : tracks;
  return choices[Math.min(choices.length - 1, Math.floor(random() * choices.length))]!;
};

/** How long two playlists overlap on a phase change (s). */
export const MUSIC_CROSSFADE_SECONDS = 1.5;
/** The music's level under a Round's end and the Results (a share of full). */
export const MUSIC_DUCK_GAIN = 0.35;
/** How fast the music ducks and comes back (s, a time constant). */
export const MUSIC_DUCK_SECONDS = 0.25;
/** How long the music takes to fade out when leaving the Match (s). */
export const MUSIC_FADE_OUT_SECONDS = 1.2;

/** What the player needs of an `<audio>` element. */
export interface MusicElement {
  src: string;
  preload: string;
  play(): Promise<void> | void;
  pause(): void;
  addEventListener(type: "ended", listener: () => void): void;
}

/** What the player needs of an `AudioContext`: a structural slice, so tests can stand one in. */
export interface MusicContext {
  readonly currentTime: number;
  readonly destination: AudioNode;
  createGain(): GainNode;
  createMediaElementSource(element: HTMLMediaElement): AudioNode;
}

export interface MusicPlayerConfig {
  context: MusicContext;
  createElement?: () => MusicElement;
  random?: () => number;
  /** Runs `run` after `ms`: a faded-out element's pause. Defaults to `setTimeout`. */
  defer?: (run: () => void, ms: number) => void;
}

interface Deck {
  element: MusicElement;
  gain: GainNode;
  /** What this deck is playing, `null` while it is idle or fading out. */
  playlist: Playlist | null;
  /** Bumped on every new job, so a pause scheduled for an old one is ignored. */
  job: number;
}

/**
 * Two decks, so a phase change crossfades: the idle deck takes the new
 * playlist and fades in while the other fades out and pauses. A track that
 * ends is followed by another from its playlist, never the same one twice
 * in a row. At zero volume the music pauses rather than playing silently.
 * An autoplay refusal is retried by {@link resume}, on the next gesture.
 */
export class MusicPlayer {
  private readonly context: MusicContext;
  private readonly random: () => number;
  private readonly defer: (run: () => void, ms: number) => void;
  private readonly volume: GainNode;
  private readonly duck: GainNode;
  private readonly decks: [Deck, Deck];
  private active: 0 | 1 = 0;
  private readonly last: Partial<Record<Playlist, string>> = {};
  private level = 1;
  private current: MatchPhase | null = null;

  constructor({
    context,
    createElement = () => new Audio(),
    random = Math.random,
    defer = (run, ms) => {
      setTimeout(run, ms);
    },
  }: MusicPlayerConfig) {
    this.context = context;
    this.random = random;
    this.defer = defer;
    this.volume = context.createGain();
    this.volume.connect(context.destination);
    this.duck = context.createGain();
    this.duck.connect(this.volume);
    this.decks = [this.createDeck(createElement()), this.createDeck(createElement())];
  }

  /** The phase the music last followed; `null` before any, and after {@link stop}. */
  get phase(): MatchPhase | null {
    return this.current;
  }

  /** What `phase` calls for; `null` fades the music out. */
  setPhase(phase: MatchPhase | null): void {
    if (phase === null) {
      this.stop();
      return;
    }
    this.current = phase;
    const want = musicFor(phase);
    const now = this.context.currentTime;
    this.duck.gain.setTargetAtTime(want.ducked ? MUSIC_DUCK_GAIN : 1, now, MUSIC_DUCK_SECONDS);
    const current = this.decks[this.active];
    if (current.playlist === want.playlist) return;
    this.active = this.active === 0 ? 1 : 0;
    const incoming = this.decks[this.active];
    incoming.job += 1;
    incoming.gain.gain.setTargetAtTime(1, now, MUSIC_CROSSFADE_SECONDS / 4);
    this.load(incoming, want.playlist);
    this.release(current, MUSIC_CROSSFADE_SECONDS);
  }

  /** MASTER × MUSIC as a linear gain. */
  setVolume(gain: number): void {
    const was = this.level;
    this.level = gain;
    this.volume.gain.setTargetAtTime(gain, this.context.currentTime, MUSIC_DUCK_SECONDS);
    const deck = this.decks[this.active];
    if (gain <= 0 && was > 0) {
      for (const each of this.decks) each.element.pause();
    } else if (gain > 0 && was <= 0 && deck.playlist) {
      this.play(deck);
    }
  }

  /** Tries again to play what should be playing: after a gesture, when the browser refused before one. */
  resume(): void {
    const deck = this.decks[this.active];
    if (deck.playlist) this.play(deck);
  }

  /** Fades out and pauses. */
  stop(): void {
    this.current = null;
    for (const deck of this.decks) this.release(deck, MUSIC_FADE_OUT_SECONDS);
  }

  private createDeck(element: MusicElement): Deck {
    element.preload = "auto";
    const gain = this.context.createGain();
    gain.gain.value = 0;
    this.context.createMediaElementSource(element as unknown as HTMLMediaElement).connect(gain);
    gain.connect(this.duck);
    const deck: Deck = { element, gain, playlist: null, job: 0 };
    element.addEventListener("ended", () => {
      if (deck.playlist && deck === this.decks[this.active]) this.load(deck, deck.playlist);
    });
    return deck;
  }

  private load(deck: Deck, playlist: Playlist): void {
    const track = nextTrack(MUSIC_PLAYLISTS[playlist], this.last[playlist], this.random);
    this.last[playlist] = track;
    deck.playlist = playlist;
    deck.element.src = `${SOUNDS_BASE_URL}${track}`;
    this.play(deck);
  }

  private play(deck: Deck): void {
    if (this.level <= 0) return;
    try {
      // A refusal before any gesture is expected: `resume` retries it.
      void Promise.resolve(deck.element.play()).catch(() => {});
    } catch {
      // Some browsers throw instead of rejecting; the same retry applies.
    }
  }

  private release(deck: Deck, seconds: number): void {
    if (deck.playlist === null) return;
    deck.playlist = null;
    const job = ++deck.job;
    deck.gain.gain.setTargetAtTime(0, this.context.currentTime, seconds / 4);
    this.defer(() => {
      if (deck.job === job) deck.element.pause();
    }, seconds * 1000);
  }
}

let player: MusicPlayer | null | undefined;

/**
 * The page's one music player, on the shared context, at the stored MASTER ×
 * MUSIC and following every change to them; `null` without Web Audio.
 */
export const musicPlayer = (): MusicPlayer | null => {
  if (player === undefined) {
    const context = sharedAudioContext();
    player = context ? new MusicPlayer({ context }) : null;
    if (player) {
      const created = player;
      const storage = browserStorage();
      created.setVolume(musicGain(readAudioVolumes(storage)));
      subscribeAudioVolumes((volumes) => created.setVolume(musicGain(volumes)), storage);
    }
  }
  return player;
};

/**
 * Where the music should be: a Match's `phase`, or `null` outside any Match,
 * which is the Lobby's playlist, the app's own music.
 */
export const setMusicPhase = (phase: MatchPhase | null, of: () => MusicPlayer | null = musicPlayer): void => {
  of()?.setPhase(phase ?? "LOBBY");
};

const GESTURES = ["pointerdown", "keydown"] as const;

/**
 * Starts the app's music on the first gesture (a browser plays nothing before
 * one), unless a Match already chose what plays. Every later gesture resumes
 * the context and retries a play the browser refused. Returns the uninstall.
 */
export const startAppMusic = (
  target: EventTarget,
  of: () => MusicPlayer | null = musicPlayer,
  contextOf: () => { readonly state: string; resume(): Promise<void> } | null = sharedAudioContext,
): (() => void) => {
  const onGesture = (): void => {
    const music = of();
    const context = contextOf();
    if (!music || !context) return;
    if (context.state !== "running") context.resume().catch(() => {});
    if (music.phase === null) music.setPhase("LOBBY");
    else music.resume();
  };
  for (const type of GESTURES) target.addEventListener(type, onGesture, true);
  return () => {
    for (const type of GESTURES) target.removeEventListener(type, onGesture, true);
  };
};
