// GENERATED by `pnpm convert:kaykit` — do not hand-edit.
// KayKit, every folder (369 shapes, textured: neutral + four colours),
// seated on the Asset pivot: footprints measured with the real shared
// reader off the converted bytes. Socketless (free placement, the
// propModule precedent) — sockets come after eyeballing in the builder.
// Re-run the script to regenerate.
import type { AssetModuleDef } from "./assetModules.js";

export const KAYKIT_MODULE_DEFS: AssetModuleDef[] = [
  {
    id: "kaykit_arch_blue",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 1.875, y: 1.85, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_green",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 1.875, y: 1.85, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_red",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 1.875, y: 1.85, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_tall_blue",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.875, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_tall_green",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.875, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_tall_red",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.875, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_tall_yellow",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.875, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_wide_blue",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.9, z: 0 }, halfExtents: { x: 2.875, y: 1.9, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_wide_green",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.9, z: 0 }, halfExtents: { x: 2.875, y: 1.9, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_wide_red",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.9, z: 0 }, halfExtents: { x: 2.875, y: 1.9, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_wide_yellow",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.9, z: 0 }, halfExtents: { x: 2.875, y: 1.9, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_arch_yellow",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 1.875, y: 1.85, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_ball",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_ball_blue",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_ball_green",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_ball_red",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_ball_yellow",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x1",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x1_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x1_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x1_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x1_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x2",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x2_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x2_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x2_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x2_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x4",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x4_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x4_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x4_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_1x1x4_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x1",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x1_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x1_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x1_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x1_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x2",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x2_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x2_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x2_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x2_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x4",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x4_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x4_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x4_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_2x1x4_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x1",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x1_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x1_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x1_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x1_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x2",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x2_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x2_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x2_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x2_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1.5, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x4",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x4_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x4_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x4_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_3x1x4_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1.5, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x1",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x1_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x1_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x1_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x1_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x2",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x2_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x2_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x2_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x2_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x4",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x4_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x4_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x4_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_barrier_4x1x4_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_large_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_large_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_large_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_large_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_medium_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.3, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_medium_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.3, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_medium_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.3, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_medium_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.3, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_small_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.1, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_small_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.1, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_small_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.1, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_bracing_small_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.3, z: 0 }, halfExtents: { x: 0.1, y: 0.3, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_button_base_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.16, z: 0 }, halfExtents: { x: 0.875, y: 0.16, z: 0.875 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_button_base_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.16, z: 0 }, halfExtents: { x: 0.875, y: 0.16, z: 0.875 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_button_base_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.16, z: 0 }, halfExtents: { x: 0.875, y: 0.16, z: 0.875 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_button_base_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.16, z: 0 }, halfExtents: { x: 0.875, y: 0.16, z: 0.875 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_cone",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.325, z: 0 }, halfExtents: { x: 0.25, y: 0.325, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_cone_blue",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.325, z: 0 }, halfExtents: { x: 0.25, y: 0.325, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_cone_green",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.325, z: 0 }, halfExtents: { x: 0.25, y: 0.325, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_cone_red",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.325, z: 0 }, halfExtents: { x: 0.25, y: 0.325, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_cone_yellow",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.325, z: 0 }, halfExtents: { x: 0.25, y: 0.325, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_diamond_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.426, z: 0 }, halfExtents: { x: 0.538, y: 0.426, z: 0.514 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_diamond_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.426, z: 0 }, halfExtents: { x: 0.538, y: 0.426, z: 0.514 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_diamond_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.426, z: 0 }, halfExtents: { x: 0.538, y: 0.426, z: 0.514 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_diamond_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.426, z: 0 }, halfExtents: { x: 0.538, y: 0.426, z: 0.514 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_A_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.032, z: 0 }, halfExtents: { x: 0.3, y: 1.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_A_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.032, z: 0 }, halfExtents: { x: 0.3, y: 1.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_A_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.032, z: 0 }, halfExtents: { x: 0.3, y: 1.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_A_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.032, z: 0 }, halfExtents: { x: 0.3, y: 1.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_B_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.532, z: 0 }, halfExtents: { x: 0.3, y: 1.532, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_B_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.532, z: 0 }, halfExtents: { x: 0.3, y: 1.532, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_B_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.532, z: 0 }, halfExtents: { x: 0.3, y: 1.532, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_B_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.532, z: 0 }, halfExtents: { x: 0.3, y: 1.532, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_C_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 2.032, z: 0 }, halfExtents: { x: 0.3, y: 2.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_C_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 2.032, z: 0 }, halfExtents: { x: 0.3, y: 2.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_C_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 2.032, z: 0 }, halfExtents: { x: 0.3, y: 2.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_flag_C_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 2.032, z: 0 }, halfExtents: { x: 0.3, y: 2.032, z: 0.812 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_floor_wood_1x1",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.25, z: 0 }, halfExtents: { x: 0.5, y: 0.25, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_floor_wood_2x6",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.25, z: 0 }, halfExtents: { x: 3, y: 0.25, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_floor_wood_4x4",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.25, z: 0 }, halfExtents: { x: 2, y: 0.25, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_heart_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.423, z: 0 }, halfExtents: { x: 0.54, y: 0.423, z: 0.265 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_heart_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.423, z: 0 }, halfExtents: { x: 0.54, y: 0.423, z: 0.265 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_heart_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.423, z: 0 }, halfExtents: { x: 0.54, y: 0.423, z: 0.265 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_heart_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.423, z: 0 }, halfExtents: { x: 0.54, y: 0.423, z: 0.265 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_angled_blue",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.127, z: 0 }, halfExtents: { x: 1.875, y: 2.127, z: 1.254 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_angled_green",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.127, z: 0 }, halfExtents: { x: 1.875, y: 2.127, z: 1.254 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_angled_red",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.127, z: 0 }, halfExtents: { x: 1.875, y: 2.127, z: 1.254 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_angled_yellow",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.127, z: 0 }, halfExtents: { x: 1.875, y: 2.127, z: 1.254 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_blue",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.7, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_green",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.7, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_red",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.7, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_hoop_yellow",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.35, z: 0 }, halfExtents: { x: 1.7, y: 2.35, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_floor_base_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.864, z: 0 }, halfExtents: { x: 0.4, y: 0.864, z: 0.6 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_floor_base_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.864, z: 0 }, halfExtents: { x: 0.4, y: 0.864, z: 0.6 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_floor_base_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.864, z: 0 }, halfExtents: { x: 0.4, y: 0.864, z: 0.6 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_floor_base_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.864, z: 0 }, halfExtents: { x: 0.4, y: 0.864, z: 0.6 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_A_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.4, y: 0.6, z: 0.546 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_A_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.4, y: 0.6, z: 0.546 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_A_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.4, y: 0.6, z: 0.546 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_A_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.4, y: 0.6, z: 0.546 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_B_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.5, y: 0.6, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_B_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.5, y: 0.6, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_B_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.5, y: 0.6, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_lever_wall_base_B_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 0.5, y: 0.6, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_1x1x1",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.4, y: 0.5, z: 0.4 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_1x1x2",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.4, y: 1, z: 0.4 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_1x1x4",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.4, y: 2, z: 0.4 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_1x1x8",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 4, z: 0 }, halfExtents: { x: 0.4, y: 4, z: 0.4 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_2x2x2",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.8, y: 1, z: 0.8 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_2x2x4",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 0.8, y: 2, z: 0.8 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pillar_2x2x8",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 4, z: 0 }, halfExtents: { x: 0.8, y: 4, z: 0.8 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_A_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_A_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_A_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_A_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_B_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.495, z: 0 }, halfExtents: { x: 1, y: 1.495, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_B_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.495, z: 0 }, halfExtents: { x: 1, y: 1.495, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_B_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.495, z: 0 }, halfExtents: { x: 1, y: 1.495, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_180_B_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.495, z: 0 }, halfExtents: { x: 1, y: 1.495, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_A_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_A_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_A_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_A_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_B_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_B_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_B_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_90_B_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1.5, z: 0 }, halfExtents: { x: 1, y: 1.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_end_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.2, y: 0.5, z: 1.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_end_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.2, y: 0.5, z: 1.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_end_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.2, y: 0.5, z: 1.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_end_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.2, y: 0.5, z: 1.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_A_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_A_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_A_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_A_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_B_blue",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_B_green",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_B_red",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_pipe_straight_B_yellow",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_1x1x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_1x1x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_1x1x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_1x1x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_2x2x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x2x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_4x4x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x2x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_6x6x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_2x2x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_2x2x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_2x2x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_2x2x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_4x4x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_4x4x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_4x4x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_arrow_4x4x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_1x1x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_1x1x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_1x1x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_1x1x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_2x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_2x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_2x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_decorative_2x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_hole_6x6x1_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_hole_6x6x1_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_hole_6x6x1_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_hole_6x6x1_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 1, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x4x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x4x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x4x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x4x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x6x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x6x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x6x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_2x6x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 1, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 2, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x4x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x4x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x4x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x4x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x6x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x6x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x6x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_4x6x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 2, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x2x2_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x2x2_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x2x2_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x2x2_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 3, y: 1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x4x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x4x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x4x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x4x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x6x4_blue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x6x4_green",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x6x4_red",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_slope_6x6x4_yellow",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2, z: 0 }, halfExtents: { x: 3, y: 2, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_wood_1x1x1",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_power_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.602, z: 0 }, halfExtents: { x: 0.445, y: 0.602, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_power_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.602, z: 0 }, halfExtents: { x: 0.445, y: 0.602, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_power_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.602, z: 0 }, halfExtents: { x: 0.445, y: 0.602, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_power_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.602, z: 0 }, halfExtents: { x: 0.445, y: 0.602, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_double_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_double_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_double_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_double_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_padded_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1.051, y: 0.6, z: 1.051 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_padded_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1.051, y: 0.6, z: 1.051 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_padded_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1.051, y: 0.6, z: 1.051 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_padded_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1.051, y: 0.6, z: 1.051 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_single_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_single_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_single_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_corner_single_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_double_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_double_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_double_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_double_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_padded_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.301 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_padded_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.301 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_padded_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.301 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_padded_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.301 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_single_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_single_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_single_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_railing_straight_single_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.6, z: 0 }, halfExtents: { x: 1, y: 0.6, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_sign",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.628, z: 0 }, halfExtents: { x: 0.383, y: 0.628, z: 0.378 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_stand_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_stand_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_stand_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_stand_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.5, y: 1, z: 0.2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_wall_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_wall_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_wall_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrow_wall_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_left",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_left_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_left_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_left_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_left_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_right",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_right_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_right_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_right_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_arrows_right_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.75, z: 0 }, halfExtents: { x: 2.7, y: 0.75, z: 0.339 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_finish",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.25, z: 0 }, halfExtents: { x: 2.7, y: 2.25, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_signage_finish_wide",
    category: "gate",
    footprint: {
      bounds: { center: { x: 0, y: 2.25, z: 0 }, halfExtents: { x: 4.7, y: 2.25, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_spring",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 1.1, z: 0 }, halfExtents: { x: 0.5, y: 1.1, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 3.05, z: 0 }, halfExtents: { x: 0.5, y: 0.4, z: 0.5 } },
      height: 10,
    },
  },
  {
    id: "kaykit_spring_pad_blue",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.75, y: 0.5, z: 0.75 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 0.75, y: 0.4, z: 0.75 } },
      height: 6,
    },
  },
  {
    id: "kaykit_spring_pad_green",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.75, y: 0.5, z: 0.75 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 0.75, y: 0.4, z: 0.75 } },
      height: 6,
    },
  },
  {
    id: "kaykit_spring_pad_red",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.75, y: 0.5, z: 0.75 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 0.75, y: 0.4, z: 0.75 } },
      height: 6,
    },
  },
  {
    id: "kaykit_spring_pad_yellow",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.75, y: 0.5, z: 0.75 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 1.85, z: 0 }, halfExtents: { x: 0.75, y: 0.4, z: 0.75 } },
      height: 6,
    },
  },
  {
    id: "kaykit_star_blue",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.554, z: 0 }, halfExtents: { x: 0.583, y: 0.554, z: 0.224 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_star_green",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.554, z: 0 }, halfExtents: { x: 0.583, y: 0.554, z: 0.224 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_star_red",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.554, z: 0 }, halfExtents: { x: 0.583, y: 0.554, z: 0.224 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_star_yellow",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.554, z: 0 }, halfExtents: { x: 0.583, y: 0.554, z: 0.224 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_structure_A",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.1, z: 0 }, halfExtents: { x: 1, y: 0.1, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_structure_B",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.55, z: 0 }, halfExtents: { x: 1, y: 0.55, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_structure_C",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.9, y: 1, z: 0.9 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_strut_horizontal",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 0.25, z: 0 }, halfExtents: { x: 1, y: 0.25, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_strut_vertical",
    category: "structure",
    footprint: {
      bounds: { center: { x: 0, y: 1, z: 0 }, halfExtents: { x: 0.25, y: 1, z: 0.25 } },
      clearance: 0.5,
    },
    sockets: [],
  },
];
