// GENERATED by `pnpm convert:quarters` — do not hand-edit.
// The quarter circle and quarter curve, 1×1 to 8×8 and one metre tall,
// seated on the Asset pivot: footprints measured with the real shared
// reader off the converted bytes. Socketless (free placement).
// Re-run the script to regenerate.
import type { AssetModuleDef } from "./assetModules.js";

export const QUARTER_MODULE_DEFS: AssetModuleDef[] = [
  {
    id: "kaykit_platform_quarter_circle_2x2x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_3x3x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_4x4x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2, y: 0.5, z: 2 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_5x5x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 2.5, y: 0.5, z: 2.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_6x6x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3, y: 0.5, z: 3 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_7x7x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 3.5, y: 0.5, z: 3.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_8x8x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 4, y: 0.5, z: 4 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_circle_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_1x1x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 0.5, y: 0.5, z: 0.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_3x3x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1.5, y: 0.5, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_4x4x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: -0.001, y: 0.5, z: -0.001 }, halfExtents: { x: 1.999, y: 0.5, z: 1.999 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_5x5x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: -0.001, y: 0.5, z: -0.001 }, halfExtents: { x: 2.499, y: 0.5, z: 2.499 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_6x6x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: -0.001, y: 0.5, z: -0.001 }, halfExtents: { x: 2.999, y: 0.5, z: 2.999 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_7x7x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: -0.001, y: 0.5, z: -0.001 }, halfExtents: { x: 3.499, y: 0.5, z: 3.499 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_8x8x1_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: -0.001, y: 0.5, z: -0.001 }, halfExtents: { x: 3.999, y: 0.5, z: 3.999 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "kaykit_platform_quarter_curve_blue",
    category: "platform",
    footprint: {
      bounds: { center: { x: 0, y: 0.5, z: 0 }, halfExtents: { x: 1, y: 0.5, z: 1 } },
      clearance: 0.5,
    },
    sockets: [],
  },
];

/**
 * Where each quarter piece's circle is centred, in its own frame: the corner
 * of its footprint the arc curls around. Four pieces turned 0/90/180/270°
 * about this point make a ring — what `disc` in `authoring.ts` builds.
 */
export const QUARTER_ARC_CENTRES: Readonly<Record<string, { x: number; z: number }>> = {
  kaykit_platform_quarter_circle_2x2x1_blue: { x: -1, z: -1 },
  kaykit_platform_quarter_circle_3x3x1_blue: { x: -1.5, z: -1.5 },
  kaykit_platform_quarter_circle_4x4x1_blue: { x: -2, z: -2 },
  kaykit_platform_quarter_circle_5x5x1_blue: { x: -2.5, z: -2.5 },
  kaykit_platform_quarter_circle_6x6x1_blue: { x: -3, z: -3 },
  kaykit_platform_quarter_circle_7x7x1_blue: { x: -3.5, z: -3.5 },
  kaykit_platform_quarter_circle_8x8x1_blue: { x: -4, z: -4 },
  kaykit_platform_quarter_circle_blue: { x: -0.5, z: -0.5 },
  kaykit_platform_quarter_curve_1x1x1_blue: { x: -0.5, z: -0.5 },
  kaykit_platform_quarter_curve_3x3x1_blue: { x: -1.5, z: -1.5 },
  kaykit_platform_quarter_curve_4x4x1_blue: { x: -2, z: -2 },
  kaykit_platform_quarter_curve_5x5x1_blue: { x: -2.5, z: -2.5 },
  kaykit_platform_quarter_curve_6x6x1_blue: { x: -3, z: -3 },
  kaykit_platform_quarter_curve_7x7x1_blue: { x: -3.5, z: -3.5 },
  kaykit_platform_quarter_curve_8x8x1_blue: { x: -4, z: -4 },
  kaykit_platform_quarter_curve_blue: { x: -1, z: -1 },
};
