// GENERATED by `pnpm convert:traps` — do not hand-edit.
// ImageToStl pack (86 shapes, textured as authored), seated on the
// Asset pivot and scaled 3.6×: footprints measured with the real
// shared reader off the converted bytes. Socketless (free placement).
// Re-run the script to regenerate.
import type { AssetModuleDef } from "./assetModules.js";

export const TRAP_MODULE_DEFS: AssetModuleDef[] = [
  {
    id: "trap_arch",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.019, z: 0 }, halfExtents: { x: 0.256, y: 1.019, z: 0.049 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrow",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.649, z: 0 }, halfExtents: { x: 0.071, y: 0.649, z: 0.042 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrow_2",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.649, z: 0 }, halfExtents: { x: 0.071, y: 0.649, z: 0.042 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrow_3",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.649, z: 0 }, halfExtents: { x: 0.071, y: 0.649, z: 0.042 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrowtrap",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.781, z: 0 }, halfExtents: { x: 1.396, y: 0.781, z: 5.212 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrowtrap_2",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.781, z: 0 }, halfExtents: { x: 1.396, y: 0.781, z: 5.212 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrowtrap_3",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.781, z: 0 }, halfExtents: { x: 1.396, y: 0.781, z: 5.212 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrowtrapbig",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.781, z: 0 }, halfExtents: { x: 1.396, y: 0.781, z: 6.126 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrowtrapbig_2",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.781, z: 0 }, halfExtents: { x: 1.396, y: 0.781, z: 6.126 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_arrowtrapbig_3",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.781, z: 0 }, halfExtents: { x: 1.396, y: 0.781, z: 6.126 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_ball",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.857, z: 0 }, halfExtents: { x: 0.857, y: 0.857, z: 0.857 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_ball_2",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.857, z: 0 }, halfExtents: { x: 0.857, y: 0.857, z: 0.857 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_ball_3",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.857, z: 0 }, halfExtents: { x: 0.857, y: 0.857, z: 0.857 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_ball_4",
    category: "prop",
    footprint: {
      bounds: { center: { x: 0, y: 0.857, z: 0 }, halfExtents: { x: 0.857, y: 0.857, z: 0.857 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_clay",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.309, z: 0 }, halfExtents: { x: 0.671, y: 0.308, z: 0.671 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_claybig",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.309, z: 0 }, halfExtents: { x: 1.96, y: 0.308, z: 1.964 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fence",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.064, z: 0 }, halfExtents: { x: 1.442, y: 1.064, z: 0.072 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fence_2",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.064, z: 0 }, halfExtents: { x: 1.442, y: 1.064, z: 0.072 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fence_3",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.064, z: 0 }, halfExtents: { x: 1.442, y: 1.064, z: 0.072 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencebig",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.528, z: 0 }, halfExtents: { x: 2.072, y: 1.528, z: 0.104 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencebig_2",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.528, z: 0 }, halfExtents: { x: 2.072, y: 1.528, z: 0.104 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencebig_3",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.528, z: 0 }, halfExtents: { x: 2.072, y: 1.528, z: 0.104 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencebig_4",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.019, z: 0 }, halfExtents: { x: 0.256, y: 1.019, z: 0.049 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencebig_5",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.019, z: 0 }, halfExtents: { x: 0.256, y: 1.019, z: 0.049 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencesmall",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.714, z: 0 }, halfExtents: { x: 0.968, y: 0.714, z: 0.048 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencesmall_2",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.714, z: 0 }, halfExtents: { x: 0.968, y: 0.714, z: 0.048 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_fencesmall_3",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 0.714, z: 0 }, halfExtents: { x: 0.968, y: 0.714, z: 0.048 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_hammer",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.13, z: 0 }, halfExtents: { x: 0.678, y: 1.13, z: 2.34 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_hammer_2",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.13, z: 0 }, halfExtents: { x: 0.678, y: 1.13, z: 2.34 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_hammer_3",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.13, z: 0 }, halfExtents: { x: 0.678, y: 1.13, z: 2.34 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_hammerbig",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.247, z: 0 }, halfExtents: { x: 0.829, y: 1.247, z: 2.954 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_hammerbig_2",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.247, z: 0 }, halfExtents: { x: 0.829, y: 1.247, z: 2.954 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_hammerbig_3",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.247, z: 0 }, halfExtents: { x: 0.829, y: 1.247, z: 2.954 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platform3faceshorizontal",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2.588, z: 0 }, halfExtents: { x: 4.376, y: 2.589, z: 5.04 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platform3faceshorizontal_2",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2.588, z: 0 }, halfExtents: { x: 4.376, y: 2.589, z: 5.04 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platform3faceshorizontal_3",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 2.588, z: 0 }, halfExtents: { x: 4.376, y: 2.589, z: 5.04 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platform3facesvertical",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 4.377, z: 0 }, halfExtents: { x: 2.589, y: 4.376, z: 5.04 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platform3facesvertical_2",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 4.377, z: 0 }, halfExtents: { x: 2.589, y: 4.376, z: 5.04 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platform3facesvertical_3",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 4.377, z: 0 }, halfExtents: { x: 2.589, y: 4.376, z: 5.04 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformblue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 0.708, y: 0.317, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformcirclehorizontal",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 3.552, z: 0 }, halfExtents: { x: 3.822, y: 3.552, z: 4.005 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformcirclehorizontal_2",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 3.552, z: 0 }, halfExtents: { x: 3.822, y: 3.552, z: 4.005 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformcirclehorizontal_3",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 3.552, z: 0 }, halfExtents: { x: 3.822, y: 3.552, z: 4.005 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformcirclevertical",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 3.822, z: 0 }, halfExtents: { x: 3.552, y: 3.822, z: 4.005 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformcirclevertical_2",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 3.822, z: 0 }, halfExtents: { x: 3.552, y: 3.822, z: 4.005 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformcirclevertical_3",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 3.822, z: 0 }, halfExtents: { x: 3.552, y: 3.822, z: 4.005 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformgreen",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 0.708, y: 0.317, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformred",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 0.708, y: 0.317, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformspikeblue",
    category: "floor",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.443, z: 0 }, halfExtents: { x: 0.708, y: 0.443, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformspikegreen",
    category: "floor",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.443, z: 0 }, halfExtents: { x: 0.708, y: 0.443, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformspikered",
    category: "floor",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.443, z: 0 }, halfExtents: { x: 0.708, y: 0.443, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformspringblue",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.863, z: 0 }, halfExtents: { x: 0.708, y: 0.862, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 2.575, z: 0 }, halfExtents: { x: 0.708, y: 0.4, z: 0.708 } },
      height: 6,
    },
  },
  {
    id: "trap_platformspringgreen",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.863, z: 0 }, halfExtents: { x: 0.708, y: 0.862, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 2.575, z: 0 }, halfExtents: { x: 0.708, y: 0.4, z: 0.708 } },
      height: 6,
    },
  },
  {
    id: "trap_platformspringred",
    category: "launcher",
    footprint: {
      bounds: { center: { x: 0, y: 0.863, z: 0 }, halfExtents: { x: 0.708, y: 0.862, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
    launch: {
      trigger: { center: { x: 0, y: 2.575, z: 0 }, halfExtents: { x: 0.708, y: 0.4, z: 0.708 } },
      height: 6,
    },
  },
  {
    id: "trap_platformstairblue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 0.708, y: 0.317, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformstairgreen",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 0.708, y: 0.317, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platformstairred",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 0.708, y: 0.317, z: 0.708 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platfrombigblue",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 1.99, y: 0.317, z: 1.99 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platfrombiggreen",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 1.99, y: 0.317, z: 1.99 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_platfrombigred",
    category: "floor",
    footprint: {
      bounds: { center: { x: 0, y: 0.317, z: 0 }, halfExtents: { x: 1.99, y: 0.317, z: 1.99 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_target",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.398, z: 0 }, halfExtents: { x: 1.217, y: 1.398, z: 0.797 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_target_2",
    category: "scenery",
    footprint: {
      bounds: { center: { x: 0, y: 1.398, z: 0 }, halfExtents: { x: 1.217, y: 1.398, z: 0.797 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trap",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.035, z: 0 }, halfExtents: { x: 0.375, y: 1.034, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trap_2",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.035, z: 0 }, halfExtents: { x: 0.375, y: 1.034, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trap_3",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.035, z: 0 }, halfExtents: { x: 0.375, y: 1.034, z: 0.375 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapball",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 3.759, z: 0 }, halfExtents: { x: 1.163, y: 3.759, z: 1.163 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapball_2",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 3.759, z: 0 }, halfExtents: { x: 1.163, y: 3.759, z: 1.163 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapball_3",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 3.759, z: 0 }, halfExtents: { x: 1.163, y: 3.759, z: 1.163 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcircleblue",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.205, y: 0.411, z: 0.85 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcircledoubleblue",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.205, y: 0.411, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcircledoublegreen",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.205, y: 0.411, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcircledoublered",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.205, y: 0.411, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclegreen",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.205, y: 0.411, z: 0.85 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclehorizontalblue",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.687, z: 0 }, halfExtents: { x: 0.322, y: 1.687, z: 0.322 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclehorizontalgreen",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.687, z: 0 }, halfExtents: { x: 0.322, y: 1.687, z: 0.322 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclehorizontalred",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 1.687, z: 0 }, halfExtents: { x: 0.322, y: 1.687, z: 0.322 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclehorizontalspikeblue",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 1.687, z: 0 }, halfExtents: { x: 0.442, y: 1.687, z: 0.442 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclehorizontalspikegreen",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 1.687, z: 0 }, halfExtents: { x: 0.442, y: 1.687, z: 0.442 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclehorizontalspikered",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 1.687, z: 0 }, halfExtents: { x: 0.442, y: 1.687, z: 0.442 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclered",
    category: "sweeper",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.205, y: 0.411, z: 0.85 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclespikeblue",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.247, y: 0.411, z: 0.85 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclespikedoubleblue",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.247, y: 0.411, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclespikedoublegreen",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.247, y: 0.411, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclespikedoublered",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.247, y: 0.411, z: 1.5 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclespikegreen",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.247, y: 0.411, z: 0.85 } },
      clearance: 0.5,
    },
    sockets: [],
  },
  {
    id: "trap_trapcirclespikered",
    category: "sweeper",
    hazard: "spiked",
    footprint: {
      bounds: { center: { x: 0, y: 0.411, z: 0 }, halfExtents: { x: 0.247, y: 0.411, z: 0.85 } },
      clearance: 0.5,
    },
    sockets: [],
  },
];
