export { ENVIRONMENT_ROOT_NAME, createEnvironment } from "./environment/createEnvironment.js";
export type { Environment, EnvironmentOptions } from "./environment/createEnvironment.js";
export { localBounds, lowestDrawnY, lowestMovingY } from "./environment/lowestDrawnY.js";
export { FOG_FAR_PLANE_MARGIN, fogFarPlane } from "./environment/farPlane.js";
export { DEFAULT_SUN_SHADOW } from "./environment/shadows.js";
export type { SunShadowSettings } from "./environment/shadows.js";
export { createPuffLook } from "./environment/cloudPuffs.js";
export type { PuffLook } from "./environment/cloudPuffs.js";
export { findSpinningParts, spinParts, spinRate } from "./spinningParts.js";
export { shareTextures } from "./assets/shareTextures.js";
export type { SharedTextureCache } from "./assets/shareTextures.js";
export { deckSheetGeometry, deckRectGeometry } from "./deckSheet.js";
export { loadDeckTexture, tileDeckTexture } from "./deckTexture.js";
export type { DecodeDeckImage, DeckTilingOptions } from "./deckTexture.js";
export { buildMudMass, disposeMudMass, mudDentDepth, simmerMud } from "./mud/mudMesh.js";
export type { MudMass } from "./mud/mudMesh.js";
export { motionCarry, mudOutline } from "./mud/mudShape.js";
export type { MudDeckPlacement, MudEdge } from "./mud/mudShape.js";
export { MUD_SEAT_LIFT } from "./mud/mudLook.js";
