export { ENVIRONMENT_ROOT_NAME, createEnvironment } from "./environment/createEnvironment.js";
export type { Environment, EnvironmentOptions } from "./environment/createEnvironment.js";
export { localBounds, lowestDrawnY, lowestMovingY } from "./environment/lowestDrawnY.js";
export { FOG_FAR_PLANE_MARGIN, fogFarPlane } from "./environment/farPlane.js";
export { DEFAULT_SUN_SHADOW } from "./environment/shadows.js";
export type { SunShadowSettings } from "./environment/shadows.js";
export { createPuffLook } from "./environment/cloudPuffs.js";
export type { PuffLook } from "./environment/cloudPuffs.js";
export { findSpinningParts, spinParts, spinRate } from "./spinningParts.js";
export { shareTextures } from "./assets/shareTextures.js";
export type { SharedTextureCache } from "./assets/shareTextures.js";
export { assetPartSubtree, partOf } from "./assetParts.js";
export { BeltSlats } from "./beltSlats.js";
export { templateForPlacement } from "./assetVariants.js";
export { deckSheetGeometry, deckRectGeometry } from "./deckSheet.js";
export { loadDeckTexture, tileDeckTexture } from "./deckTexture.js";
export type { DecodeDeckImage, DeckTilingOptions } from "./deckTexture.js";
export { buildMudMass, disposeMudMass, mudDentDepth, simmerMud } from "./mud/mudMesh.js";
export type { MudMass } from "./mud/mudMesh.js";
export { motionCarry, mudOutline } from "./mud/mudShape.js";
export type { MudDeckPlacement, MudEdge } from "./mud/mudShape.js";
export { MUD_SEAT_LIFT } from "./mud/mudLook.js";
export { buildIceSlab, disposeIceSlab, glintIce, iceDetailTexture } from "./ice/iceMesh.js";
export type { IceSlab } from "./ice/iceMesh.js";
export { iceGlintPose, iceGlintSites } from "./ice/iceShape.js";
export { ICE_SEAT_LIFT } from "./ice/iceLook.js";
export { BOMB_EXPLODE_LEAD_SECONDS, createBombLook, isBombTemplate, restBombLook } from "./bomb/bombLook.js";
export type { BombLook } from "./bomb/bombLook.js";
